- name: upgrade Debian family
  apt:
    upgrade: dist
    
- name: install utilities 
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - ebtables 
    - socat 
    - jq 
    - apt-transport-https 
    - ca-certificates
    - curl
    - software-properties-common
    - bash-completion 
    - ntp 
    - wget
    - logrotate
    - python-pip
  notify:
    - restart ntpd
- name: remove networkmanager
  apt:
    name: network-manager
    state: absent