- name: ensure utils are installed 
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - tar

- name: extract agent
  unarchive: 
    src: http://appcenter-docs.qingcloud.com/developer-guide/scripts/app-agent-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes
    list_files: true
    creates: /tmp/app-agent-linux-amd64/install.sh

- name: install agent
  shell: /tmp/app-agent-linux-amd64/install.sh
  args:
    chdir: /tmp/app-agent-linux-amd64/
    creates: /opt/qingcloud/app-agent/bin/exec.sh
