apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-qingcloud-hostnic
  namespace: kube-system
  labels:
    tier: node
    app: kube-qingcloud-hostnic
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: kube-qingcloud-hostnic
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: hostnic
      containers:
      - name: kube-qingcloud-hostnic
        image: dockerhub.qingcloud.com/qingcloud/hostnic-cni:v0.8.2
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: LOGLEVEL
          value: "info"

        - name: VXNETS
          value: "{{$pod_vxnets := getv "/env/pod_vxnets"}}{{if eq $pod_vxnets ""}}{{getv "/cluster/vxnet"}}{{else}}{{split $pod_vxnets " "|toJson}}{{end}}"

        - name: POOLSIZE
          value: "3"

        - name: qingcloud-cfg
          mountPath: /etc/qingcloud/

      - name: qingcloud-cfg
        hostPath:
          path: /etc/qingcloud/
