apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostnic
  namespace: kube-system
  labels:
    k8s-app: kube-qingcloud-hostnic
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostnic
  labels:
    k8s-app: kube-qingcloud-hostnic
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostnic
  labels:
    k8s-app: kube-qingcloud-hostnic
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hostnic
subjects:
- kind: ServiceAccount
  name: hostnic
  namespace: kube-system
