- name: install salt repo key on debian family
  apt_key:
    url: https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    state: present

- name: install salt repo on debian family
  apt_repository:
    repo: deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest {{ansible_lsb.codename}} main
    update_cache: true

- name: install salt component on debian family
  apt:
    name: "{{ item}}"
    state: latest
  with_items:
    - salt-master
    - salt-minion
    - salt-ssh
    - salt-syndic
    - salt-cloud
    - salt-api