- name: install salt repo on redhat family
  yum:
    name: https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm 
    state: present

- name: install salt on redhat family
  yum:
    name: {{ item }}
    state: present
    update_cache: true
  with_items:
    - salt-master
    - salt-minion
    - salt-ssh
    - salt-syndic
    - salt-cloud
    - salt-api