apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    k8s-app: prometheus
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  name: prometheus
  namespace: kube-system
spec:
  selector:
    k8s-app: prometheus
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 80
    targetPort: 9090
    NodePort: 30000
