apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-logging-v1
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  serviceName: "elasticsearch-logging"
  replicas: 2
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated", "value":"log", "effect":"NoSchedule"}]'
    spec:
      containers:
      - image: dockerhub.qingcloud.com/google_containers/elasticsearch:v5.4.0-1
        imagePullPolicy: IfNotPresent
        name: elasticsearch-logging
        resources:
          requests:
            cpu: 1
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
          # Forcing es instance not to schedule to the same node.
          hostPort: 9200
        - containerPort: 9300
          name: transport
          protocol: TCP
          hostPort: 9300
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "MINIMUM_MASTER_NODES"
          value: "1"
      volumes:
      - name: es-persistent-storage
        hostPath:
          path: /data/es
      nodeSelector:
          role: log
