apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  serviceName: "elasticsearch-logging"
  replicas: 2
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: elasticsearch-logging
      initContainers:
      - image: dockerhub.qingcloud.com/alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
      containers:
      - image: dockerhub.qingcloud.com/google_containers/elasticsearch:v5.5.1
        imagePullPolicy: IfNotPresent
        name: elasticsearch-logging
        resources:
          requests:
            cpu: 1
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
          # Forcing es instance not to schedule to the same node.
          hostPort: 9200
        - containerPort: 9300
          name: transport
          protocol: TCP
          hostPort: 9300
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "MINIMUM_MASTER_NODES"
          value: "2"
      volumes:
      - name: es-persistent-storage
        hostPath:
          path: /data/es
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "dedicated"
        value: "log"
        effect: NoSchedule
      nodeSelector:
          role: log
