apiVersion: extensions/v1beta2
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        qingcloud.com/update-time: ""
    spec:
      serviceAccountName: fluentd-es
      initContainers:
      - name: wait-init-es-service
        image: dockerhub.qingcloud.com/alpine:3.6
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z -v -w5 elasticsearch-logging 9200; do echo "wait elasticsearch-logging service"; sleep 2; done;']
      containers:
      - name: fluent-bit
        image: dockerhub.qingcloud.com/fluent/fluent-bit:0.12.2
        command:
        - /fluent-bit/bin/fluent-bit
        - -c
        - /fluent-bit/etc/fluent-bit.conf
        imagePullPolicy: IfNotPresent
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-logging"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /data/var/lib/docker/containers
          readOnly: true
        - name: journallog
          mountPath: /run/log/journal/
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: fluent-bit-extend-config
          mountPath: /fluent-bit/etc.d/
        ports:
        - containerPort: 24224
          name: ui
          protocol: TCP
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /data/var/lib/docker/containers
      - name: journallog
        hostPath:
          path: /run/log/journal/
      - name: fluent-bit-config
        configMap:
          name: fluent-bit
      - name: fluent-bit-extend-config
        configMap:
          name: fluent-bit-extend
          items:
          - key: extend.conf
            path: extend.conf
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "dedicated"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        effect: NoSchedule
      - key: node.cloudprovider.kubernetes.io/uninitialized
        effect: NoSchedule
        value: "true"
