apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","operator": "Exists"}]'
    spec:
      containers:
      - name: fluent-bit
        image: dockerhub.qingcloud.com/fluent/fluent-bit-kubernetes-daemonset:0.11.13
        imagePullPolicy: IfNotPresent
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-logging"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /data/var/lib/docker/containers
          readOnly: true
        ports:
        - containerPort: 24224
          name: ui
          protocol: TCP
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /data/var/lib/docker/containers
