apiVersion: v1
kind: Service
metadata:
  name: fluentbit-logging
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/name: "Fluentbit"
spec:
  ports:
  - port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    k8s-app: fluent-bit-logging
