---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heapster-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eventer-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-app: heapster
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
  template:
    metadata:
      labels:
        k8s-app: heapster
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccount: "heapster"
      containers:
        - name: heapster
          image: dockerhub.qingcloud.com/google_containers/heapster-amd64:v1.5.3
          imagePullPolicy: IfNotPresent
          command:
            - /heapster
            - "--source=kubernetes:https://kubernetes.default.svc?insecure=true&kubeletHttps=true&useServiceAccount=true&kubeletPort=10250"
            - --sink=elasticsearch:http://elasticsearch-logging:9200
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: usr-ca-certs
              mountPath: /usr/share/ca-certificates
              readOnly: true
        - name: eventer
          image: dockerhub.qingcloud.com/google_containers/heapster-amd64:v1.5.3
          imagePullPolicy: IfNotPresent
          command:
            - /eventer
            - "--source=kubernetes:https://kubernetes.default.svc?insecure=true&kubeletHttps=true&useServiceAccount=true&kubeletPort=10250"
            - --sink=elasticsearch:http://elasticsearch-logging:9200
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: usr-ca-certs
              mountPath: /usr/share/ca-certificates
              readOnly: true
        - image: dockerhub.qingcloud.com/google_containers/addon-resizer:1.8.1
          imagePullPolicy: IfNotPresent
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi
          volumeMounts:
          - name: heapster-config-volume
            mountPath: /etc/config
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --config-dir=/etc/config
            - --cpu=80m
            - --extra-cpu=0.5m
            - --memory=140Mi
            - --extra-memory=4Mi
            - --threshold=5
            - --deployment=heapster
            - --container=heapster
            - --poll-period=300000
            - --estimator=exponential
        - image: dockerhub.qingcloud.com/google_containers/addon-resizer:1.8.1
          imagePullPolicy: IfNotPresent
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi
          volumeMounts:
          - name: eventer-config-volume
            mountPath: /etc/config
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --config-dir=/etc/config
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=190Mi
            - --extra-memory=0.5Ki
            - --threshold=5
            - --deployment=heapster
            - --container=eventer
            - --poll-period=300000
            - --estimator=exponential
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
        - name: usr-ca-certs
          hostPath:
            path: "/usr/share/ca-certificates"
        - name: heapster-config-volume
          configMap:
            name: heapster-config
        - name: eventer-config-volume
          configMap:
            name: eventer-config
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "dedicated"
        value: "log"
        effect: NoSchedule
      nodeSelector:
        role: log
