
- name: download kubernetes repo
  get_url:
    url: https://pek3a.qingstor.com/k8s-qingcloud/k8s/{{ kubernetes_version }}/bin/{{item}}
    dest: /usr/bin/{{item}}
    mode: 755
  with_items:
    - kubelet
    - kubectl
    - kubeadm
  
- name: install shell completion
  shell: |
    kubectl completion bash >/etc/profile.d/kubectl.sh
    kubeadm completion bash >/etc/profile.d/kubeadm.sh
 
- name: install kubelet systemd def
  copy:
    src: files/{{item}}
    dest: /etc/systemd/system/{{item}}
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - kubelet.service

- name: load service def
  systemd:
    daemon_reload: yes
    name: kubelet
    enabled: yes

- name: pull docker images
  docker_image:
    name: dockerhub.qingcloud.com/google_containers/{{item.name}}:{{item.version}}
    state: present
  with_items:
    - { name: "hyperkube-amd64", version: "{{kubernetes_version}}" }
    - { name: "etcd-amd64", version: "3.0.17" }
    - { name: "pause-amd64:3.0", version: "3.0"}
    - { name: "k8s-dns-kube-dns-amd64", version: "1.14.5"}
    - { name: "k8s-dns-dnsmasq-nanny-amd64", version: "1.14.5"}
    - { name: "k8s-dns-sidecar-amd64", version: "1.14.5"}
    - { name: "kube-addon-manager:", version: "v6.4-beta.2"}
    - { name: "addon-resizer", version: "1.7"}

