apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ssh-authkey
  labels:
    k8s-app: ssh-authkey
spec:
  template:
    metadata:
      labels:
        k8s-app: ssh-authkey
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","operator": "Exists"}]'
    spec:
      containers:
      - name: file-sync
        image: dockerhub.qingcloud.com/qingcloud/file-sync:0.6
        imagePullPolicy: IfNotPresent
        env:
          - name:  FROM_FILE
            value: "/container/ssh/authorized_keys"
          - name:  TO_FILE
            value: "/host/ssh/authorized_keys"
        volumeMounts:
        - name: ssh
          mountPath: /container/ssh
        - name: host-ssh
          mountPath: /host/ssh
      volumes:
      - name: ssh
        configMap:
          name: authorizedkeys
      - name: host-ssh
        hostPath:
          path: "/root/.ssh"
