apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerbox
spec:
  replicas: 1
  template:
      metadata:
        labels:
          app: dockerbox
      spec:
        containers:
          - name: dockerbox
            image: dockerhub.qingcloud.com/qingcloud/dockerbox
            command: [ "darkhttpd","/work --port=80" ]
            ports:
              - name: web
                containerPort: 80
                protocol: TCP
        imagePullSecrets:
            - name: myregistrykey