apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qingcloud-web
spec:
  replicas: 1
  template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: web
            image: dockerhub.qingcloud.com/docker/nginx
            ports:
              - name: web
                containerPort: 80
                protocol: TCP
            volumeMounts:
              - name: html-volume
                mountPath: "/usr/share/nginx/html"
        volumes:
           - name: html-volume
             hostPath:
               path: "/data/html"
        imagePullSecrets:
            - name: qingcloud-registrykey