apiVersion: v1
kind: Service
metadata:
  name: qingcloud-web
  annotations:
    service.beta.kubernetes.io/qingcloud-load-balancer-eip-ids: "eip-a1klhfqk"
    service.beta.kubernetes.io/qingcloud-load-balancer-type: "1"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer