apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qingcloud-web
spec:
  replicas: 1
  template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: web
            image: dockerhub.qingcloud.com/qingcloud/dockerbox
            command: [ "darkhttpd","/work --port=80" ]
            ports:
              - name: web
                containerPort: 80
                protocol: TCP
            volumeMounts:
              - name: html-volume
                mountPath: "/usr/share/nginx/html"
        volumes:
           - name: html-volume
             emptyDir: {}
        imagePullSecrets:
                    - name: myregistrykey