---
apiVersion: v1
kind: Service
metadata:
  name: statefulnginx
  labels:
    app: statefulnginx
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: statefulnginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulweb
spec:
  serviceName: "statefulnginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: statefulnginx
    spec:
      containers:
      - name: nginx
        image: dockerhub.qingcloud.com/docker/nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      imagePullSecrets:
        - name: myregistrykey
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.alpha.kubernetes.io/storage-class: qingcloud-storageclass
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi