apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    component: kube-addon-manager
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    # When updating version also bump it in:
    # - cluster/images/hyperkube/static-pods/addon-manager-singlenode.json
    # - cluster/images/hyperkube/static-pods/addon-manager-multinode.json
    # - test/kubemark/resources/manifests/kube-addon-manager.yaml
    image: dockerhub.qingcloud.com/google_containers/kube-addon-manager:v8.6
    imagePullPolicy: IfNotPresent
    command:
    - /bin/bash
    - -c
    - /opt/kube-addons.sh
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: addons
      readOnly: true
  volumes:
  - name: addons
    hostPath:
      path: /etc/kubernetes/
