apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: qingcloud-volume-provisioner
    tier: control-plane
  name: qingcloud-volume-provisioner
  namespace: kube-system
spec:
  containers:
  - command:
    - qingcloud-volume-provisioner
    - --v=${KUBE_LOG_LEVEL}
    - --kubeconfig=/etc/kubernetes/admin.conf
    - --qingcloud_config=/etc/qingcloud/client.yaml
    image: dockerhub.qingcloud.com/qingcloud/qingcloud-volume-provisioner:v1.3.2
    imagePullPolicy: IfNotPresent
    name: qingcloud-cloud-controller-manager
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: k8s
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: certs
    - mountPath: /etc/qingcloud
      name: qingcloud
      readOnly: true
  hostNetwork: true
  volumes:
  - name: k8s
    hostPath:
      path: /etc/kubernetes
  - name: certs
    hostPath:
      path: /etc/ssl/certs
  - name: qingcloud
    hostPath:
      path: /etc/qingcloud
