- name: remove old version of docker
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  
- name: install docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: install docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable
    update_cache: true

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - docker-ce
  notify:
    - restart docker