- name: setup Ubuntu image
  include_tasks: debian.yaml
  when: ansible_os_family == 'Debian'


- name: setup Centos images
  include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'

- name: setup docker python client
  pip:
    name: docker-py
    
- name: enable docker
  service:
    name: docker
    enabled: yes

- name: setup logrotate
  copy:
    src: files/{{item}}
    dest: /etc/logrotate.d/{{item}}
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - docker-containers

- name: docker login
  docker_login:
    username: guest
    password: guest
    registry_url: https://dockerhub.qingcloud.com
    state: present

- name: setup storage driver
  copy:
    src: files/{{item}}
    dest: /etc/docker/{{item}}
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - daemon.json
  notify:
    - restart docker

- name: enable service def
  systemd:
    name: docker
    enabled: yes