apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-log
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        k8s-app: clean-log
    spec:
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
          - name: elasticsearch-curator
            image: dockerhub.qingcloud.com/qingcloud/elasticsearch-curator:5.1.1
            command:
            - /usr/bin/curator
            - --config
            - /etc/kubernetes/curator/config.yaml
            - /etc/kubernetes/curator/action.yaml
            volumeMounts:
            - mountPath: /etc/kubernetes/
              name: config
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - hostPath:
              path: /etc/kubernetes/
            name: config