kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: qingcloud-storageclass
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/qingcloud-volume
parameters:
  type: "3"
